window.GRN_SAMPLE_DATA = {
  ok: true,
  generated_at_ist: '2026-07-08 09:30:00',
  meta: {
    app_name: 'MW GRN Dock to Stock Dashboard',
    refresh_minutes: 30,
    timezone: 'Asia/Kolkata',
    last_refresh_ist: '2026-07-08 09:30:00'
  },
  overall_tat: [
    {
      vehicle_number: 'MH12AB1234',
      invoice_number: 'INV-1001',
      invoice_date: '2026-07-07 00:00:00',
      sku_code: 'SKU-HAIR-001',
      sku_name: 'Hair Gummies',
      supplier_vendor: 'Vendor A',
      dock: 'Dock 1',
      warehouse: 'Mother Warehouse',
      reporting_time_ist: '2026-07-08 06:00:00',
      unloading_start_time_ist: '2026-07-08 07:00:00',
      grn_time_ist: '2026-07-08 10:00:00',
      putaway_time_ist: '2026-07-08 14:30:00',
      reporting_to_unloading_days: 0.042,
      unloading_to_grn_days: 0.125,
      grn_to_putaway_days: 0.188,
      dock_to_stock_days: 0.354,
      grn_number: 'GRN-001',
      expected_quantity: 100,
      grn_quantity: 100,
      putaway_quantity: 100,
      status: 'Completed',
      sla_breach: 'No',
      sla_breach_stage: '',
      match_status: 'exact'
    },
    {
      vehicle_number: 'MH14CD5678',
      invoice_number: 'INV-1002',
      invoice_date: '2026-07-07 00:00:00',
      sku_code: 'SKU-SKIN-002',
      sku_name: 'Skin Serum',
      supplier_vendor: 'Vendor B',
      dock: 'Dock 2',
      warehouse: 'Mother Warehouse',
      reporting_time_ist: '2026-07-08 03:30:00',
      unloading_start_time_ist: '2026-07-08 04:15:00',
      grn_time_ist: '2026-07-08 14:45:00',
      putaway_time_ist: '',
      reporting_to_unloading_days: 0.031,
      unloading_to_grn_days: 0.438,
      grn_to_putaway_days: '',
      dock_to_stock_days: '',
      grn_number: 'GRN-002',
      expected_quantity: 75,
      grn_quantity: 75,
      putaway_quantity: '',
      status: 'Pending putaway',
      sla_breach: 'Yes',
      sla_breach_stage: 'unloading_to_grn',
      match_status: 'exact'
    },
    {
      vehicle_number: 'MH01EF9012',
      invoice_number: 'INV-1003',
      invoice_date: '2026-07-07 00:00:00',
      sku_code: 'SKU-VIT-003',
      sku_name: 'Vitamin Tablets',
      supplier_vendor: 'Vendor C',
      dock: 'Dock 3',
      warehouse: 'Mother Warehouse',
      reporting_time_ist: '2026-07-08 01:45:00',
      unloading_start_time_ist: '2026-07-08 02:20:00',
      grn_time_ist: '',
      putaway_time_ist: '',
      reporting_to_unloading_days: 0.024,
      unloading_to_grn_days: '',
      grn_to_putaway_days: '',
      dock_to_stock_days: '',
      grn_number: '',
      expected_quantity: 120,
      grn_quantity: '',
      putaway_quantity: '',
      status: 'Pending GRN',
      sla_breach: 'Yes',
      sla_breach_stage: 'unloading_to_grn_pending',
      match_status: 'unmatched'
    },
    {
      vehicle_number: 'MH03IJ7890',
      invoice_number: 'INV-1005-AX',
      invoice_date: '2026-07-07 00:00:00',
      sku_code: 'SKU-SLEEP-005',
      sku_name: 'Sleep Spray',
      supplier_vendor: 'Vendor E',
      dock: 'Dock 1',
      warehouse: 'Mother Warehouse',
      reporting_time_ist: '2026-07-08 08:10:00',
      unloading_start_time_ist: '2026-07-08 09:00:00',
      grn_time_ist: '2026-07-08 11:15:00',
      putaway_time_ist: '2026-07-08 16:00:00',
      reporting_to_unloading_days: 0.035,
      unloading_to_grn_days: 0.094,
      grn_to_putaway_days: 0.198,
      dock_to_stock_days: 0.326,
      grn_number: 'GRN-005',
      expected_quantity: 90,
      grn_quantity: 90,
      putaway_quantity: 90,
      status: 'Completed',
      sla_breach: 'No',
      sla_breach_stage: '',
      match_status: 'needs_review_fuzzy_invoice_0.94'
    }
  ],
  pending_actions: [
    {
      vehicle_number: 'MH14CD5678',
      invoice_number: 'INV-1002',
      sku_code: 'SKU-SKIN-002',
      sku_name: 'Skin Serum',
      pending_stage: 'Putaway pending',
      pending_since_ist: '2026-07-08 14:45:00',
      age_hours: 5.7,
      ageing_bucket: '4-8 hrs',
      expected_quantity: 75,
      grn_number: 'GRN-002',
      grn_quantity: 75,
      action_required: 'Complete putaway',
      match_status: 'exact'
    },
    {
      vehicle_number: 'MH01EF9012',
      invoice_number: 'INV-1003',
      sku_code: 'SKU-VIT-003',
      sku_name: 'Vitamin Tablets',
      pending_stage: 'GRN not done',
      pending_since_ist: '2026-07-08 02:20:00',
      age_hours: 12.2,
      ageing_bucket: '8-24 hrs',
      expected_quantity: 120,
      grn_number: '',
      grn_quantity: '',
      action_required: 'Create GRN',
      match_status: 'unmatched'
    }
  ],
  priority_grn_queue: [
    {
      sku_code: 'SKU-VIT-003',
      sku_name: 'Vitamin Tablets',
      doi_days: 0.67,
      priority: 'P0',
      mother_stock_in_hand: 20,
      sales_7d: 210,
      average_daily_sales: 30,
      zero_stock: 'No',
      high_velocity: 'No',
      pending_grn_quantity: 120,
      invoice_number: 'INV-1003',
      vehicle_number: 'MH01EF9012',
      recommended_action: 'GRN immediately and hand to putaway',
      match_status: 'unmatched'
    }
  ],
  sla_summary: {
    avg_unloading_to_grn_days: 0.219,
    avg_grn_to_putaway_days: 0.193,
    avg_dock_to_stock_days: 0.34,
    sla_breach_count: 2,
    p0_pending_count: 1,
    p1_pending_count: 0,
    completed_count: 2,
    pending_grn_count: 1,
    pending_putaway_count: 1,
    last_refresh_ist: '2026-07-08 09:30:00'
  },
  source_status: [
    {
      report_type: 'grn',
      subject: 'Export Job Complete - GRN',
      status: 'success',
      message_id: 'sample-grn',
      report_timestamp_ist: '2026-07-08 09:00:00',
      row_count: 3,
      fetched_at_ist: '2026-07-08 09:30:00',
      error: ''
    },
    {
      report_type: 'putaway',
      subject: 'Export Job Complete - GRN/Gatepass to Putaway',
      status: 'success',
      message_id: 'sample-putaway',
      report_timestamp_ist: '2026-07-08 09:05:00',
      row_count: 2,
      fetched_at_ist: '2026-07-08 09:30:00',
      error: ''
    },
    {
      report_type: 'inventory',
      subject: 'Export Job Complete - FG INVENTORY REPORT',
      status: 'success',
      message_id: 'sample-inventory',
      report_timestamp_ist: '2026-07-08 09:10:00',
      row_count: 10,
      fetched_at_ist: '2026-07-08 09:30:00',
      error: ''
    }
  ],
  error_log: []
};
